import Foundation

/// Row shape of the `dive` table, the cached deep-dive dossier for one place
/// (synthesized once, read many; lore/docs/03-ARCHITECTURE.md §7).
///
/// Live PostgREST columns: `place_id`, `narrative`, `timeline`, `links`,
/// `media`, `source`. `links` and `media` are jsonb OBJECTS (not arrays) and
/// every jsonb column can be null, so each is decoded leniently: a null,
/// absent, or unexpectedly-shaped value defaults to empty and NEVER throws, so
/// one odd row can never fail the whole dossier (the bug that broke the
/// paywalled deep dive on device).
struct Dive: Codable, Hashable {
    let placeID: String
    /// Long-form docent narrative (the DiveSheet reader body).
    let narrative: String?
    /// Horizontal timeline events, oldest first.
    let timeline: [TimelineEvent]
    /// Source / read-more links, a jsonb OBJECT
    /// ({"website": "...", "source_url": "...", "wikipedia_title": "..."}).
    let links: DiveLinks
    /// The dossier's lead image reference, resolved from
    /// `media.wikipedia_title` via the Wikipedia summary API (the same source
    /// the culture portraits use). Also a jsonb OBJECT.
    let media: DiveMediaRef
    /// Synthesis provenance tag.
    let source: String?
    /// Storage path of the pre-rendered narration (`narration` public bucket),
    /// generated by tools/narration. Nil = no studio audio yet; the app falls
    /// back to on-device TTS so audio works everywhere while cities roll out.
    let audioPath: String?
    /// Duration of the pre-rendered narration, for the player affordance.
    let audioSeconds: Int?

    enum CodingKeys: String, CodingKey {
        case narrative, timeline, links, media, source
        case placeID = "place_id"
        case audioPath = "audio_path"
        case audioSeconds = "audio_seconds"
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        placeID = try container.decode(String.self, forKey: .placeID)
        narrative = try container.decodeIfPresent(String.self, forKey: .narrative)
        timeline = (try? container.decodeIfPresent([TimelineEvent].self, forKey: .timeline)) ?? []
        links = (try? container.decodeIfPresent(DiveLinks.self, forKey: .links)) ?? DiveLinks()
        media = (try? container.decodeIfPresent(DiveMediaRef.self, forKey: .media)) ?? DiveMediaRef()
        source = try container.decodeIfPresent(String.self, forKey: .source)
        audioPath = (try? container.decodeIfPresent(String.self, forKey: .audioPath)) ?? nil
        audioSeconds = (try? container.decodeIfPresent(Int.self, forKey: .audioSeconds)) ?? nil
    }

    init(
        placeID: String,
        narrative: String?,
        timeline: [TimelineEvent] = [],
        links: DiveLinks = DiveLinks(),
        media: DiveMediaRef = DiveMediaRef(),
        source: String? = nil,
        audioPath: String? = nil,
        audioSeconds: Int? = nil
    ) {
        self.placeID = placeID
        self.narrative = narrative
        self.timeline = timeline
        self.links = links
        self.media = media
        self.source = source
        self.audioPath = audioPath
        self.audioSeconds = audioSeconds
    }

    /// Public URL of the studio narration in the `narration` bucket, when this
    /// dive has one.
    var audioURL: URL? {
        guard let audioPath, !audioPath.isEmpty else { return nil }
        return Config.storageURL.appending(path: "object/public/narration/\(audioPath)")
    }
}

/// One node on the dive timeline: `{ "year": 1973, "title": "…",
/// "detail": "…", "emoji": "🏗️" }`.
struct TimelineEvent: Codable, Hashable, Identifiable {
    let year: Int
    let title: String
    let detail: String?
    let emoji: String?

    var id: String { "\(year)-\(title)" }
}

/// `dive.links`, a jsonb object. Values render only when they are valid,
/// external citation/read-more links; malformed source rows stay hidden.
struct DiveLinks: Codable, Hashable {
    let website: String?
    let sourceURLString: String?
    let wikipediaTitle: String?

    enum CodingKeys: String, CodingKey {
        case website
        case sourceURLString = "source_url"
        case wikipediaTitle = "wikipedia_title"
    }

    init(
        website: String? = nil,
        sourceURLString: String? = nil,
        wikipediaTitle: String? = nil
    ) {
        self.website = website
        self.sourceURLString = sourceURLString
        self.wikipediaTitle = wikipediaTitle
    }

    /// Official or place-owned website URL when the dossier carries one.
    var websiteURL: URL? {
        Self.validHTTPSURL(website)
    }

    /// Explicit source-record URL from `links.source_url`, separate from the
    /// older `dive.source` label field.
    var sourceRecordURL: URL? {
        Self.validHTTPSURL(sourceURLString)
    }

    /// The read-more Wikipedia article URL for this dive, if it names one.
    var wikipediaURL: URL? {
        guard let title = wikipediaTitle,
              let encoded = title.replacingOccurrences(of: " ", with: "_")
                .addingPercentEncoding(withAllowedCharacters: .urlPathAllowed)
        else { return nil }
        return URL(string: "https://en.wikipedia.org/wiki/\(encoded)")
    }

    private static func validHTTPSURL(_ raw: String?) -> URL? {
        guard
            let raw = raw?.trimmingCharacters(in: .whitespacesAndNewlines),
            !raw.isEmpty,
            let url = URL(string: raw),
            url.scheme?.lowercased() == "https",
            url.host != nil
        else { return nil }
        return url
    }
}

enum WikipediaTitleList {
    static func cleaned(_ values: [String?]) -> [String] {
        var seen: Set<String> = []
        var titles: [String] = []
        for value in values {
            let trimmed = value?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
            guard !trimmed.isEmpty else { continue }
            let key = trimmed.folding(options: [.caseInsensitive, .diacriticInsensitive], locale: .current)
            if seen.insert(key).inserted {
                titles.append(trimmed)
            }
        }
        return titles
    }
}

/// `dive.media`, a jsonb object naming the Wikipedia article(s) whose images
/// can form the dossier gallery. Current rows usually carry one
/// `wikipedia_title`; newer content can provide `wikipedia_titles` or
/// `gallery_wikipedia_titles` and the app will render a carousel.
struct DiveMediaRef: Codable, Hashable {
    let wikipediaTitle: String?
    let wikipediaTitles: [String]

    enum CodingKeys: String, CodingKey {
        case wikipediaTitle = "wikipedia_title"
        case wikipediaTitles = "wikipedia_titles"
        case galleryWikipediaTitle = "gallery_wikipedia_title"
        case galleryWikipediaTitles = "gallery_wikipedia_titles"
        case imageWikipediaTitles = "image_wikipedia_titles"
    }

    init(wikipediaTitle: String? = nil, wikipediaTitles: [String] = []) {
        let titles = WikipediaTitleList.cleaned([wikipediaTitle] + wikipediaTitles.map { Optional($0) })
        self.wikipediaTitle = titles.first
        self.wikipediaTitles = titles
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let primary = try container.decodeIfPresent(String.self, forKey: .wikipediaTitle)
        let galleryPrimary = try container.decodeIfPresent(String.self, forKey: .galleryWikipediaTitle)
        let titles = WikipediaTitleList.cleaned(
            [primary, galleryPrimary]
            + Self.decodeTitles(in: container, forKey: .wikipediaTitles).map { Optional($0) }
            + Self.decodeTitles(in: container, forKey: .galleryWikipediaTitles).map { Optional($0) }
            + Self.decodeTitles(in: container, forKey: .imageWikipediaTitles).map { Optional($0) }
        )
        wikipediaTitle = titles.first
        wikipediaTitles = titles
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(wikipediaTitle, forKey: .wikipediaTitle)
        if wikipediaTitles.count > 1 {
            try container.encode(wikipediaTitles, forKey: .wikipediaTitles)
        }
    }

    private static func decodeTitles(
        in container: KeyedDecodingContainer<CodingKeys>,
        forKey key: CodingKeys
    ) -> [String] {
        if let values = try? container.decodeIfPresent([String].self, forKey: key) {
            return values
        }
        if let value = try? container.decodeIfPresent(String.self, forKey: key) {
            return [value]
        }
        return []
    }
}
